version: '3.3'

services:
  db:
    image: mysql:5.7
    ports:
    - "4306:3306"
    container_name: "start-medeia-db"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: "start-media-dev"
    volumes:
      - "./html/wp-content:/var/www/html/wp-content:cached"
      - ./config/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

volumes:
  db_data:
